name: ox_call
description: XChat WebRTC calling module
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_webrtc: ^1.2.1
  permission_handler: ^11.0.0
  isar:
    git:
      url: https://github.com/wcat7/isar.git
      path: packages/isar
      ref: 4.0.3-fix
  isar_flutter_libs:
    git:
      url: https://github.com/wcat7/isar.git
      path: packages/isar_flutter_libs
      ref: 4.0.3-fix


  # Core dependencies
  chatcore:
    path: ../../0xchat-core
  nostr_core_dart:
    path: ../../nostr-dart
  ox_module_service:
    path: ../ox_module_service
  ox_common:
    path: ../ox_common
  ox_cache_manager:
    path: ../ox_cache_manager

  # Audio session for background keep-alive
  audio_session: ^0.1.18

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0